language: cpp
os:
  - linux
  - osx
  - windows
compiler:
  - clang
  - gcc
matrix:
  include:
    # Windows x64 builds (MSVC)
    - os: windows
      env:
        - MATRIX_EVAL="CC=CL.exe && CXX=CL.exe"

before_install:
  - eval "${MATRIX_EVAL}"
install:
  - cd test
script:
  - make c
  - make c_no_sse
  - make cpp
  - make cpp_no_sse
